### ISSUE TITLE
The tray icon doesn't appear in the 64-bit linux deployment

### ISSUE THREAD

**Issue by karagog** [karagog/Gryptonite#73]
For whatever reason the tray icon is not showing when I built the release version in 64 bit.

**Comment by karagog** [comment]
This is a problem with Qt. I updated from 5.4.0 to 5.4.2 and this problem appeared. Looks like I'll be deploying with an older version of Qt until they figure this out.

**Comment by Auronius** [comment]
Would be better to deploy with Qt4. There is difficult to change font sizes and other interface preferences for Qt5 based applications on some Linux Desktop environments.

**Comment by karagog** [comment]
I suggest opening another bug if there are specific issues; this bug is closed.
