### ISSUE TITLE
Browse to URL

### ISSUE THREAD

**Issue by metarhyme** [karagog/Gryptonite#76]
Password Safe has a feature:  (https://i2.wp.com/metarhyme.files.wordpress.com/2016/07/browse.gif?ssl=1&w=450) right click drop down list with "Browse to URL."  AutoType may not work but Browse to URL always works.  Of course, Password Safe dislikes Linux.  This is a Gryptonite feature request.

**Comment by karagog** [comment]
Hello and thank you for the feature request. If I understand you correctly, this is already a feature of Gryptonite :)  If the item has a "URL" field, you can right-click it and say "pop out". Alternately, if you make it a "favorite" you can right-click the tray icon and when you open the item it will browse to the URL. Note that you must enable this "auto-launch URL" feature in the settings (on by default).
